coreapp/urls.py
from django.urls import path
from . import views

app_name = "coreapp"

urlpatterns = [
    path('', views.chart_view, name='home'),
    path('list/', views.index_view, name='country'), 
    path('search/', views.search_view, name='search'), 
    path('boxplot/', views.eda_boxplot_view, name='boxplot'),
    path('scatterplot/', views.eda_scatterplot_view, name='scatterplot'),
    path('compare/', views.country_comparison_view, name='compare'),

]

pandas_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('coreapp.urls')),
    path('admin/', admin.site.urls),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}COVID Dashboard{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    {% block extra_css %}{% endblock %}
</head>
<body>

<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">COVID Info</a>

    <div class="navbar-nav">
      <a class="nav-link" href="{% url 'coreapp:home' %}">Chart</a>
      <a class="nav-link" href="{% url 'coreapp:country' %}">Country List</a>
      <a class="nav-link" href="{% url 'coreapp:boxplot' %}">Boxplot</a>
      <a class="nav-link" href="{% url 'coreapp:scatterplot' %}">Scatter Plot</a>
      <a class="nav-link" href="{% url 'coreapp:compare' %}">Country Comparison</a> 

    </div>

    <form method="get" action="{% url 'coreapp:search' %}" class="d-flex ms-auto" role="search">
        <input type="text" name="q" value="{{ query }}" placeholder="Search country..." class="form-control me-2" aria-label="Search" required>
        <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
  </div>
</nav>

<!-- Main Content -->
<div class="container mt-4">
    {% block content %}{% endblock %}
</div>

<!-- Footer -->
<footer class="bg-light text-center py-3 mt-5">
    <div class="container">
        <span class="text-muted">&copy; 2025 COVID Info Dashboard</span>
    </div>
</footer>

<!-- JS Scripts (placed at end for performance) -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>


{% block extra_js %}{% endblock %}
</body>
</html>